"use server";
import {revalidatePath} from "next/cache";import {getCurrentSession} from "@/application/session";import {validatePersonalPersonName} from "@/application/personal";import {getServerPersonalUseCases} from "@/application/server";
type PersonalEventType="birthday"|"anniversary"|"custom";type ImperialMonth=1|2|3|4|5|6|7|8|9|10|11|12;const yearlyRecurrence={frequency:"yearly" as const,interval:1 as const};
function date(fd:FormData){return{year:Number(fd.get("year")),month:Number(fd.get("month")) as ImperialMonth,day:Number(fd.get("day"))}};
function eventInput(fd:FormData,mode:"create"|"update"){const type=String(fd.get("type")??"custom") as PersonalEventType;const title=String(fd.get("title")??"").trim();const eventDate=date(fd);const notes=String(fd.get("notes")??"").trim();const personId=String(fd.get("personalPersonId")??"").trim();const isRecurring=type==="birthday"||type==="anniversary"||fd.get("recurrence")==="yearly";const base={type,title,date:eventDate};if(mode==="update")return{...base,notes:notes||null,personalPersonId:personId||null,recurrence:isRecurring?yearlyRecurrence:null};return isRecurring?{...base,recurrence:yearlyRecurrence}:{...base}};
async function sessionOrThrow(){const s=await getCurrentSession();if(!s)throw new Error("SIGN_IN_REQUIRED");return s}
export async function createPersonalEventAction(fd:FormData){const s=await sessionOrThrow();await getServerPersonalUseCases().createEvent(s.userId,eventInput(fd,"create"));revalidatePath("/personal");revalidatePath("/")}
export async function updatePersonalEventAction(fd:FormData){const s=await sessionOrThrow();await getServerPersonalUseCases().updateEvent(s.userId,String(fd.get("id")??""),eventInput(fd,"update"));revalidatePath("/personal");revalidatePath("/")}
export async function deletePersonalEventAction(fd:FormData){const s=await sessionOrThrow();await getServerPersonalUseCases().deleteEvent(s.userId,String(fd.get("id")??""));revalidatePath("/personal");revalidatePath("/")}
export async function createPersonalPersonAction(fd:FormData){const s=await sessionOrThrow();const name=String(fd.get("name")??"").trim();validatePersonalPersonName(name);await getServerPersonalUseCases().createPerson(s.userId,{name});revalidatePath("/personal")}
export async function createMemoryAction(fd:FormData){const s=await sessionOrThrow();const title=String(fd.get("title")??"").trim();const input={date:date(fd),text:String(fd.get("text")??""),tags:[],mediaIds:[],personIds:[],eventIds:[],personalEventIds:[]};await getServerPersonalUseCases().createMemory(s.userId,title?{...input,title}:{...input});revalidatePath("/personal");revalidatePath("/")}
export async function updateMemoryAction(fd:FormData){const s=await sessionOrThrow();await getServerPersonalUseCases().updateMemory(s.userId,String(fd.get("id")??""),{date:date(fd),title:String(fd.get("title")??"").trim()||null,text:String(fd.get("text")??"")});revalidatePath("/personal");revalidatePath("/")}
export async function deleteMemoryAction(fd:FormData){const s=await sessionOrThrow();await getServerPersonalUseCases().deleteMemory(s.userId,String(fd.get("id")??""));revalidatePath("/personal");revalidatePath("/")}
