import type {Event} from "../domain/event/types";
import type {HistoricalPeriod} from "../domain/period/types";
import type {Person} from "../domain/person/types";
import type {Source} from "../domain/source/types";

const exact=(year:number,month:number,day:number,calendar="solar_hijri")=>({originalCalendar:calendar,originalDate:`${year}-${month}-${day}`,imperialDate:{year:year+1180,month:month as 1|2|3|4|5|6|7|8|9|10|11|12,day},precision:"EXACT" as const});

export const seedSources:readonly Source[]=[
{id:"source-constitutional",title:"Encyclopaedia Iranica — Constitutional Revolution, iii: The Constitution",author:"Encyclopaedia Iranica",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/constitutional-revolution-iii/",referenceDetail:"Constitutional developments and the December 1925 constituent-assembly transition.",language:"en"},
{id:"source-ahmad-shah",title:"Encyclopaedia Iranica — Aḥmad Shah Qājār",author:"Encyclopaedia Iranica",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/ahmad-shah-qajar-1909-1925-the-seventh-and-last-ruler-of-the-qajar-dynasty/",referenceDetail:"The 1925 constituent assembly decision transferring the crown to Reżā Shah and his male heirs.",language:"en"},
{id:"source-allied",title:"Encyclopaedia Iranica — Anglo-Iranian Relations, iii: Pahlavi Period",author:"Encyclopaedia Iranica",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/anglo-iranian-relations-iii-pahlavi-period/",referenceDetail:"Allied entry into Iran on 25 August 1941 and Reżā Shah's abdication on 16 September 1941.",language:"en"},
{id:"source-coup",title:"Encyclopaedia Iranica — Coup d’État of 1332 Š./1953",author:"Mark J. Gasiorowski",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/coup-detat-1953/",referenceDetail:"The overthrow of Moḥammad Moṣaddeq on 28 Mordād 1332 Š./19 August 1953.",language:"en"},
{id:"source-coronation",title:"Encyclopaedia Iranica — Crown Jewels of Persia",author:"Encyclopaedia Iranica",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/crown-jewels-of-persia-the-assemblage-of-jewels-collected-by-the-kings-of-persia-kept-now-in-the-bank-e-markazi-e-iran-/",referenceDetail:"Coronation of Moḥammad-Reżā Shah on 4 Ābān 1346 Š./26 October 1967.",language:"en"},
{id:"source-revolution",title:"Encyclopaedia Iranica — Class System, vi: Classes in the Pahlavi Period",author:"Encyclopaedia Iranica",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/class-system-vi/",referenceDetail:"Collapse of the government on 22 Bahman 1357 Š./11 February 1979 during the Iranian Revolution.",language:"en"}
];

export const seedPeriods:readonly HistoricalPeriod[]=[
{id:"period-constitutional",slug:"constitutional-era",name:{fa:"دوران مشروطه",en:"Constitutional Era"},summary:{fa:"دگرگونی سیاسی و حقوقی آغاز سدهٔ بیستم که به شکل‌گیری نظام مشروطه انجامید.",en:"The early twentieth-century political and legal transformation that established a constitutional system."},startDate:exact(1285,5,14),endDate:exact(1304,9,21),eventIds:["event-constitutional-decree","event-reza-shah-accession"],personIds:["person-mozzafar","person-mohammad-ali","person-reza"],sourceIds:["source-constitutional","source-ahmad-shah"],mediaIds:[],status:"APPROVED",createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"period-pahlavi",slug:"pahlavi-period",name:{fa:"دورهٔ پهلوی",en:"Pahlavi Period"},summary:{fa:"دورهٔ ۱۹۲۵ تا ۱۹۷۹ در تاریخ معاصر ایران، از انتقال سلطنت قاجار تا پایان حکومت پهلوی.",en:"The 1925–1979 period in modern Iranian history, from the transfer of the crown from Qajar to the end of Pahlavi rule."},startDate:exact(1304,9,21),endDate:exact(1357,11,22),eventIds:["event-reza-shah-accession","event-allied-invasion","event-reza-shah-abdication","event-coup-1953","event-coronation-1967","event-revolution-1979"],personIds:["person-reza","person-mohammad-reza","person-mossadegh"],sourceIds:["source-ahmad-shah","source-allied","source-coup","source-coronation","source-revolution"],mediaIds:[],status:"APPROVED",createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"}
];

export const seedPeople:readonly Person[]=[
{id:"person-mozzafar",slug:"mozaffar-al-din-shah",status:"APPROVED",visibility:"PUBLIC",name:{fa:"مظفرالدین‌شاه قاجار",en:"Moẓaffar al-Din Shah Qajar"},aliases:[],shortBio:{fa:"شاه قاجار در زمان صدور فرمان مشروطیت.",en:"Qajar shah at the time of the constitutional decree."},tags:["qajar","constitutional"],periodIds:["period-constitutional"],eventIds:["event-constitutional-decree"],relatedPersonIds:["person-mohammad-ali"],sourceIds:["source-constitutional"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"person-mohammad-ali",slug:"mohammad-ali-shah-qajar",status:"APPROVED",visibility:"PUBLIC",name:{fa:"محمدعلی‌شاه قاجار",en:"Moḥammad-ʿAli Shah Qajar"},aliases:[],shortBio:{fa:"شاه قاجار پس از مظفرالدین‌شاه و از چهره‌های دورهٔ مشروطه.",en:"Qajar shah who succeeded Moẓaffar al-Din Shah and was a major figure of the constitutional era."},tags:["qajar","constitutional"],periodIds:["period-constitutional"],eventIds:[],relatedPersonIds:["person-mozzafar"],sourceIds:["source-constitutional"],mediaIds:[],createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"person-reza",slug:"reza-shah-pahlavi",status:"APPROVED",visibility:"PUBLIC",name:{fa:"رضاشاه پهلوی",en:"Reżā Shah Pahlavi"},aliases:[],shortBio:{fa:"پادشاه پهلوی از ۱۹۲۵ تا ۱۹۴۱.",en:"Pahlavi monarch from 1925 to 1941."},tags:["pahlavi","modern-history"],periodIds:["period-pahlavi"],eventIds:["event-reza-shah-accession","event-allied-invasion","event-reza-shah-abdication"],relatedPersonIds:["person-mohammad-reza"],sourceIds:["source-ahmad-shah","source-allied"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"person-mohammad-reza",slug:"mohammad-reza-shah-pahlavi",status:"APPROVED",visibility:"PUBLIC",name:{fa:"محمدرضاشاه پهلوی",en:"Moḥammad-Reżā Shah Pahlavi"},aliases:[],shortBio:{fa:"پادشاه پهلوی از ۱۹۴۱ تا ۱۹۷۹.",en:"Pahlavi monarch from 1941 to 1979."},tags:["pahlavi","modern-history"],periodIds:["period-pahlavi"],eventIds:["event-reza-shah-abdication","event-coronation-1967","event-revolution-1979"],relatedPersonIds:["person-reza"],sourceIds:["source-allied","source-coronation","source-revolution"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"person-mossadegh",slug:"mohammad-mossadegh",status:"APPROVED",visibility:"PUBLIC",name:{fa:"محمد مصدق",en:"Moḥammad Moṣaddeq"},aliases:[],shortBio:{fa:"نخست‌وزیر ایران در دورهٔ منتهی به کودتای ۲۸ مرداد ۱۳۳۲.",en:"Prime minister of Iran during the period leading to the 1953 coup."},tags:["national-front","oil-nationalization"],periodIds:["period-pahlavi"],eventIds:["event-coup-1953"],relatedPersonIds:["person-mohammad-reza"],sourceIds:["source-coup"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"}
];

export const seedEvents:readonly Event[]=[
{id:"event-constitutional-decree",slug:"constitutional-decree-1906",status:"APPROVED",visibility:"PUBLIC",title:{fa:"صدور فرمان مشروطیت",en:"Constitutional Decree"},shortTitle:{fa:"فرمان مشروطیت",en:"Constitutional Decree"},summary:{fa:"مظفرالدین‌شاه فرمان آغاز فرایند مشروطه و تشکیل مجلس را صادر کرد.",en:"Moẓaffar al-Din Shah issued the decree that initiated the constitutional process."},description:{fa:"این فرمان در ۱۴ مرداد ۱۲۸۵ صادر شد و به تشکیل مجلس و شکل‌گیری نظام مشروطه انجامید.",en:"The decree was issued on 14 Mordād 1285 and initiated the constitutional process that led to the Majles and the constitutional system."},dates:[{start:exact(1285,5,14)}],category:"national",tags:["constitutional-revolution","qajar"],personIds:["person-mozzafar"],periodIds:["period-constitutional"],relatedEventIds:[],sourceIds:["source-constitutional"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"event-reza-shah-accession",slug:"reza-shah-crown-1925",status:"APPROVED",visibility:"PUBLIC",title:{fa:"انتقال سلطنت به رضاشاه",en:"Transfer of the Crown to Reżā Shah"},shortTitle:{fa:"انتقال سلطنت",en:"Transfer of the Crown"},summary:{fa:"در آذر ۱۳۰۴، مجلس مؤسسان سلطنت را به رضاشاه و جانشینان او واگذار کرد.",en:"In December 1925, the constituent assembly transferred the crown to Reżā Shah and his heirs."},description:{fa:"این تصمیم به پایان سلطنت قاجار و آغاز دورهٔ پهلوی انجامید.",en:"The decision ended Qajar rule and began the Pahlavi period."},dates:[{start:exact(1304,9,21)}],category:"dynastic",tags:["qajar","pahlavi"],personIds:["person-reza"],periodIds:["period-constitutional","period-pahlavi"],relatedEventIds:[],sourceIds:["source-ahmad-shah"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"event-allied-invasion",slug:"allied-invasion-1941",status:"APPROVED",visibility:"PUBLIC",title:{fa:"ورود نیروهای بریتانیا و شوروی به ایران",en:"Allied Invasion of Iran"},shortTitle:{fa:"ورود نیروهای متفقین",en:"Allied Invasion"},summary:{fa:"نیروهای بریتانیا و شوروی در ۳ شهریور ۱۳۲۰ وارد ایران شدند.",en:"British and Soviet forces entered Iran on 25 August 1941."},description:{fa:"این رویداد در جریان جنگ جهانی دوم رخ داد و پس از آن تحولات سیاسی مهمی در ایران روی داد.",en:"The invasion occurred during the Second World War and was followed by major political changes in Iran."},dates:[{start:exact(1320,6,3)}],category:"historical",tags:["world-war-ii","pahlavi"],personIds:["person-reza","person-mohammad-reza"],periodIds:["period-pahlavi"],relatedEventIds:["event-reza-shah-abdication"],sourceIds:["source-allied"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"event-reza-shah-abdication",slug:"reza-shah-abdication-1941",status:"APPROVED",visibility:"PUBLIC",title:{fa:"کناره‌گیری رضاشاه",en:"Reżā Shah's Abdication"},shortTitle:{fa:"کناره‌گیری رضاشاه",en:"Abdication"},summary:{fa:"رضاشاه در ۲۵ شهریور ۱۳۲۰ از سلطنت کناره‌گیری کرد و محمدرضاشاه جانشین او شد.",en:"Reżā Shah abdicated on 16 September 1941 and was succeeded by Moḥammad-Reżā Shah."},description:{fa:"کناره‌گیری پس از ورود نیروهای متفقین در اوت ۱۹۴۱ رخ داد.",en:"The abdication followed the Allied invasion of Iran in August 1941."},dates:[{start:exact(1320,6,25)}],category:"dynastic",tags:["pahlavi","succession","world-war-ii"],personIds:["person-reza","person-mohammad-reza"],periodIds:["period-pahlavi"],relatedEventIds:["event-allied-invasion"],sourceIds:["source-allied"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"event-coup-1953",slug:"coup-1953",status:"APPROVED",visibility:"PUBLIC",title:{fa:"کودتای ۲۸ مرداد",en:"Coup d’État of 1953"},shortTitle:{fa:"۲۸ مرداد ۱۳۳۲",en:"28 Mordād 1332"},summary:{fa:"دولت محمد مصدق در ۲۸ مرداد ۱۳۳۲ سرنگون شد.",en:"The government of Moḥammad Moṣaddeq was overthrown on 28 Mordād 1332."},description:{fa:"این رویداد در ۱۹ اوت ۱۹۵۳ رخ داد و یکی از نقاط مهم تاریخ سیاسی معاصر ایران است.",en:"The coup took place on 19 August 1953 and is a major event in modern Iranian political history."},dates:[{start:exact(1332,5,28)}],category:"historical",tags:["1953","coup","mossadegh"],personIds:["person-mossadegh","person-mohammad-reza"],periodIds:["period-pahlavi"],relatedEventIds:[],sourceIds:["source-coup"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"event-coronation-1967",slug:"mohammad-reza-coronation-1967",status:"APPROVED",visibility:"PUBLIC",title:{fa:"تاج‌گذاری محمدرضاشاه",en:"Coronation of Moḥammad-Reżā Shah"},shortTitle:{fa:"تاج‌گذاری",en:"Coronation"},summary:{fa:"محمدرضاشاه در ۴ آبان ۱۳۴۶ تاج‌گذاری کرد.",en:"Moḥammad-Reżā Shah was crowned on 4 Ābān 1346."},description:{fa:"این مراسم در تهران برگزار شد و بخشی از آیین‌های سلطنتی دورهٔ پهلوی بود.",en:"The ceremony took place in Tehran and formed part of the royal ceremonies of the Pahlavi period."},dates:[{start:exact(1346,8,4)}],category:"royal",tags:["pahlavi","coronation","1967"],personIds:["person-mohammad-reza"],periodIds:["period-pahlavi"],relatedEventIds:[],sourceIds:["source-coronation"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"event-revolution-1979",slug:"government-collapse-1979",status:"APPROVED",visibility:"PUBLIC",title:{fa:"سقوط دولت در جریان انقلاب ۱۳۵۷",en:"Government Collapse During the 1979 Revolution"},shortTitle:{fa:"پایان حکومت پهلوی",en:"End of Pahlavi Rule"},summary:{fa:"در ۲۲ بهمن ۱۳۵۷ دولت فروپاشید و حکومت پهلوی پایان یافت.",en:"On 22 Bahman 1357 the government collapsed and Pahlavi rule ended."},description:{fa:"این تاریخ نقطهٔ پایان حکومت پهلوی در مرحلهٔ نهایی انقلاب ۱۳۵۷ به شمار می‌آید.",en:"The date marks the collapse of the government and end of Pahlavi rule in the final stage of the 1979 Revolution."},dates:[{start:exact(1357,11,22)}],category:"protest_movement",tags:["1979","revolution","pahlavi"],personIds:["person-mohammad-reza"],periodIds:["period-pahlavi"],relatedEventIds:[],sourceIds:["source-revolution"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"}
];

export const seedPublicContent={events:seedEvents,people:seedPeople,periods:seedPeriods,sources:seedSources};
