import type {Event} from "../domain/event/types";
import type {HistoricalPeriod} from "../domain/period/types";
import type {Person} from "../domain/person/types";
import type {Source} from "../domain/source/types";

const exact=(year:number,month:number,day:number,calendar="solar_hijri")=>({originalCalendar:calendar,originalDate:`${year}-${month}-${day}`,imperialDate:{year:year+1180,month:month as 1|2|3|4|5|6|7|8|9|10|11|12,day},precision:"EXACT" as const});

export const seedSources:readonly Source[]=[
{id:"source-constitutional",title:"Encyclopaedia Iranica — Constitutional Revolution, iii: The Constitution",author:"Encyclopaedia Iranica",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/constitutional-revolution-iii/",referenceDetail:"Constitutional developments and the December 1925 constituent-assembly transition.",language:"en"},
{id:"source-ahmad-shah",title:"Encyclopaedia Iranica — Aḥmad Shah Qājār",author:"Encyclopaedia Iranica",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/ahmad-shah-qajar-1909-1925-the-seventh-and-last-ruler-of-the-qajar-dynasty/",referenceDetail:"The 1925 constituent assembly decision transferring the crown to Reżā Shah and his male heirs.",language:"en"},
{id:"source-allied",title:"Encyclopaedia Iranica — Anglo-Iranian Relations, iii: Pahlavi Period",author:"Encyclopaedia Iranica",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/anglo-iranian-relations-iii-pahlavi-period/",referenceDetail:"Allied entry into Iran on 25 August 1941 and Reżā Shah's abdication on 16 September 1941.",language:"en"},
{id:"source-coup",title:"Encyclopaedia Iranica — Coup d’État of 1332 Š./1953",author:"Mark J. Gasiorowski",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/coup-detat-1953/",referenceDetail:"The overthrow of Moḥammad Moṣaddeq on 28 Mordād 1332 Š./19 August 1953.",language:"en"},
{id:"source-coronation",title:"Encyclopaedia Iranica — Crown Jewels of Persia",author:"Encyclopaedia Iranica",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/crown-jewels-of-persia-the-assemblage-of-jewels-collected-by-the-kings-of-persia-kept-now-in-the-bank-e-markazi-e-iran-/",referenceDetail:"Coronation of Moḥammad-Reżā Shah on 4 Ābān 1346 Š./26 October 1967.",language:"en"},
{id:"source-revolution",title:"Encyclopaedia Iranica — Class System, vi: Classes in the Pahlavi Period",author:"Encyclopaedia Iranica",publisher:"Encyclopaedia Iranica",sourceType:"reputable_reference",url:"https://www.iranicaonline.org/articles/class-system-vi/",referenceDetail:"Collapse of the government on 22 Bahman 1357 Š./11 February 1979 during the Iranian Revolution.",language:"en"}
];

export const seedPeriods:readonly HistoricalPeriod[]=[
{id:"period-constitutional",slug:"constitutional-era",name:{fa:"دوران مشروطه",en:"Constitutional Era"},summary:{fa:"دگرگونی سیاسی و حقوقی آغاز سدهٔ بیستم که به شکل‌گیری نظام مشروطه انجامید.",en:"The early twentieth-century political and legal transformation that established a constitutional system."},startDate:exact(1285,5,14),endDate:exact(1304,9,21),eventIds:[],personIds:["person-mozzafar","person-mohammad-ali","person-reza"],sourceIds:["source-constitutional","source-ahmad-shah"],mediaIds:[],status:"APPROVED",createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"period-pahlavi",slug:"pahlavi-period",name:{fa:"دورهٔ پهلوی",en:"Pahlavi Period"},summary:{fa:"دورهٔ ۱۹۲۵ تا ۱۹۷۹ در تاریخ معاصر ایران، از انتقال سلطنت قاجار تا پایان حکومت پهلوی.",en:"The 1925–1979 period in modern Iranian history, from the transfer of the crown from Qajar to the end of Pahlavi rule."},startDate:exact(1304,9,21),endDate:exact(1357,11,22),eventIds:[],personIds:["person-reza","person-mohammad-reza","person-mossadegh"],sourceIds:["source-ahmad-shah","source-allied","source-coup","source-coronation","source-revolution"],mediaIds:[],status:"APPROVED",createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"}
];

export const seedPeople:readonly Person[]=[
{id:"person-mozzafar",slug:"mozaffar-al-din-shah",status:"APPROVED",visibility:"PUBLIC",name:{fa:"مظفرالدین‌شاه قاجار",en:"Moẓaffar al-Din Shah Qajar"},aliases:[],shortBio:{fa:"شاه قاجار در زمان صدور فرمان مشروطیت.",en:"Qajar shah at the time of the constitutional decree."},tags:["qajar","constitutional"],periodIds:["period-constitutional"],eventIds:[],relatedPersonIds:["person-mohammad-ali"],sourceIds:["source-constitutional"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"person-mohammad-ali",slug:"mohammad-ali-shah-qajar",status:"APPROVED",visibility:"PUBLIC",name:{fa:"محمدعلی‌شاه قاجار",en:"Moḥammad-ʿAli Shah Qajar"},aliases:[],shortBio:{fa:"شاه قاجار پس از مظفرالدین‌شاه و از چهره‌های دورهٔ مشروطه.",en:"Qajar shah who succeeded Moẓaffar al-Din Shah and was a major figure of the constitutional era."},tags:["qajar","constitutional"],periodIds:["period-constitutional"],eventIds:[],relatedPersonIds:["person-mozzafar"],sourceIds:["source-constitutional"],mediaIds:[],createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"person-reza",slug:"reza-shah-pahlavi",status:"APPROVED",visibility:"PUBLIC",name:{fa:"رضاشاه پهلوی",en:"Reżā Shah Pahlavi"},aliases:[],shortBio:{fa:"پادشاه پهلوی از ۱۹۲۵ تا ۱۹۴۱.",en:"Pahlavi monarch from 1925 to 1941."},tags:["pahlavi","modern-history"],periodIds:["period-pahlavi"],eventIds:[],relatedPersonIds:["person-mohammad-reza"],sourceIds:["source-ahmad-shah","source-allied"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"person-mohammad-reza",slug:"mohammad-reza-shah-pahlavi",status:"APPROVED",visibility:"PUBLIC",name:{fa:"محمدرضاشاه پهلوی",en:"Moḥammad-Reżā Shah Pahlavi"},aliases:[],shortBio:{fa:"پادشاه پهلوی از ۱۹۴۱ تا ۱۹۷۹.",en:"Pahlavi monarch from 1941 to 1979."},tags:["pahlavi","modern-history"],periodIds:["period-pahlavi"],eventIds:[],relatedPersonIds:["person-reza"],sourceIds:["source-allied","source-coronation","source-revolution"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"},
{id:"person-mossadegh",slug:"mohammad-mossadegh",status:"APPROVED",visibility:"PUBLIC",name:{fa:"محمد مصدق",en:"Moḥammad Moṣaddeq"},aliases:[],shortBio:{fa:"نخست‌وزیر ایران در دورهٔ منتهی به کودتای ۲۸ مرداد ۱۳۳۲.",en:"Prime minister of Iran during the period leading to the 1953 coup."},tags:["national-front","oil-nationalization"],periodIds:["period-pahlavi"],eventIds:[],relatedPersonIds:["person-mohammad-reza"],sourceIds:["source-coup"],mediaIds:[],featured:true,createdAt:"2026-10-03T00:00:00.000Z",updatedAt:"2026-10-03T00:00:00.000Z"}
];

export const seedEvents:readonly Event[]=[];

export const seedPublicContent={events:seedEvents,people:seedPeople,periods:seedPeriods,sources:seedSources};
