import Link from "next/link";
import { getCurrentSession } from "@/application/session";
import { personalRepository } from "@/data/db/repositories";
import { application } from "@/application/use-cases";
import { resolveLocale } from "@/application/locale";
import { AppShell } from "@/frontend/components/app-shell";
import { copy } from "@/frontend/lib/i18n";
import { imperialDateLabel } from "@/frontend/lib/format";
import { createPersonalEventAction, createPersonalPersonAction, createMemoryAction } from "@/app/actions/personal";
import { signOutAction } from "@/app/actions/auth";
import { ShareCardButton } from "@/frontend/components/share-card-button";
export const dynamic="force-dynamic";
export default async function PersonalPage({searchParams}:{searchParams?:Promise<Record<string,string|string[]|undefined>>}){
  const p=await searchParams;const locale=resolveLocale(typeof p?.lang==="string"?p.lang:undefined);const t=copy[locale];const session=await getCurrentSession();
  if(!session)return <AppShell locale={locale} active="personal"><section className="auth-card card"><div className="overline">{t.personal}</div><h1>{locale==="fa"?"لایهٔ شخصی":"Personal layer"}</h1><p className="prose">{locale==="fa"?"برای دیدن و نگهداری رویدادها و خاطرات شخصی وارد حساب شو.":"Sign in to manage your personal events and memories."}</p><div style={{display:"flex",gap:8}}><Link className="primary-button" href={`/login?lang=${locale}`}>{t.signIn}</Link><Link className="secondary-button" href={`/register?lang=${locale}`}>{t.signUp}</Link></div></section></AppShell>;
  try{
    const data=await application.personal(personalRepository).listOverview(session.userId);
    const cards=data.events.map(e=>({event:e,dto:application.shareCard(session.userId,e)}));
    return <AppShell locale={locale} active="personal">
      <section className="hero-panel"><div className="overline">{t.personal}</div><h1 style={{margin:"8px 0"}}>{session.userId.slice(0,8)}</h1><form action={signOutAction}><button className="secondary-button" type="submit">{t.logout}</button></form></section>
      <div className="two-col">
        <section className="stack"><div className="section-head"><h2>{t.addEvent}</h2></div><form className="card detail-card form-stack" action={createPersonalEventAction}><div className="field"><label>{locale==="fa"?"عنوان":"Title"}</label><input name="title" required /></div><div className="field"><label>{locale==="fa"?"نوع":"Type"}</label><select name="type" defaultValue="custom"><option value="birthday">birthday</option><option value="anniversary">anniversary</option><option value="custom">custom</option></select></div><div className="two-col"><div className="field"><label>Year</label><input name="year" type="number" defaultValue={2585} required /></div><div className="field"><label>Month</label><input name="month" type="number" min="1" max="12" defaultValue={7} required /></div></div><div className="field"><label>Day</label><input name="day" type="number" min="1" max="31" defaultValue={11} required /></div><label style={{display:"flex",gap:8,alignItems:"center"}}><input name="recurrence" value="yearly" type="checkbox" /> {locale==="fa"?"هر سال تکرار شود":"Repeat yearly"}</label><div className="field"><label>{locale==="fa"?"یادداشت":"Notes"}</label><textarea name="notes" rows={3}/></div><button className="primary-button" type="submit">{locale==="fa"?"ذخیره":"Save"}</button></form></section>
        <section className="stack"><div className="section-head"><h2>{t.addMemory}</h2></div><form className="card detail-card form-stack" action={createMemoryAction}><div className="field"><label>{locale==="fa"?"عنوان":"Title"}</label><input name="title" /></div><div className="field"><label>{locale==="fa"?"متن خاطره":"Memory"}</label><textarea name="text" rows={6} required/></div><div className="two-col"><div className="field"><label>Year</label><input name="year" type="number" defaultValue={2585} required /></div><div className="field"><label>Month</label><input name="month" type="number" min="1" max="12" defaultValue={7} required /></div></div><div className="field"><label>Day</label><input name="day" type="number" min="1" max="31" defaultValue={11} required /></div><button className="primary-button" type="submit">{locale==="fa"?"ثبت خاطره":"Save memory"}</button></form></section>
      </div>
      <section className="two-col"><form className="card detail-card form-stack" action={createPersonalPersonAction}><h2 style={{margin:0}}>{locale==="fa"?"شخص شخصی":"Personal person"}</h2><div className="field"><label>{locale==="fa"?"نام":"Name"}</label><input name="name" required /></div><button className="secondary-button" type="submit">{locale==="fa"?"افزودن":"Add"}</button></form><div className="card detail-card"><h2 style={{margin:0}}>{locale==="fa"?"افراد من":"My people"}</h2>{data.people.map(person=><div key={person.id} style={{marginTop:10}}>{person.name}</div>)}{!data.people.length?<div className="empty">{t.noResults}</div>:null}</div></section>
      <section><div className="section-head"><h2>{t.personal}</h2></div><div className="stack">{cards.map(({event,dto})=><article key={event.id} className="card detail-card"><div className="eyebrow">{event.type}</div><h3>{event.title}</h3><div className="meta-row"><span className="pill">{imperialDateLabel(event.date,locale)}</span></div><div style={{marginTop:12}}><ShareCardButton dto={dto} locale={locale}/></div></article>)}{data.memories.map(m=><article key={m.id} className="card detail-card"><div className="eyebrow">{t.memories}</div><h3>{m.title??""}</h3><p className="prose">{m.text}</p></article>)}{!data.events.length&&!data.memories.length?<div className="card empty">{t.noResults}</div>:null}</div></section>
    </AppShell>;
  }catch{return <AppShell locale={locale} active="personal"><div className="notice">{locale==="fa"?"حساب شناسایی شد، اما DATABASE_URL/دیتابیس برای لایهٔ شخصی در این محیط تنظیم نشده است.":"The account is recognized, but DATABASE_URL/database is not configured in this environment."}</div></AppShell>}
}
